name: berlinpixel
favicon: null
layout_spectrum: 0.53569
typography_spectrum: 0.57495
title: Silvester
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.6875
  lightness: 0.2331335130147636
  saturation: 0.25
  rhythmicContrast: 0.75
purpose: []
